import { Category, ResourceSectionData } from "./types";

export const categories: Category[] = [
  { id: "all", label: "All" },
  { id: "parenting", label: "Parenting" },
  { id: "selfCare", label: "Self-care" },
  { id: "recipe", label: "Quick recipe" },
];

// Temporary demo data matching the design; replace with API payloads once available.
export const resourceSections: ResourceSectionData[] = [
  {
    id: "parenting-hacks",
    title: "Parenting Hacks",
    categoryId: "parenting",
    searchPlaceholder: "Search for Parenting tips",
    resources: [
      {
        id: "quick-diaper",
        title: "Quick Diaper Change",
        description: "Use a portable changing pad and keep essentials organized.",
        image: { uri: "https://placehold.co/300x200/1E90FF/FFFFFF?text=Resource" },
        fullContent: "Lay out supplies, keep one hand on the baby, clean front to back, let skin dry, apply cream if needed, fasten a fresh diaper snugly, and dispose of the dirty one.",
        steps: [
          "Prep first.",
          "Lay the baby down safely.",
          "Clean thoroughly.",
          "Apply cream if needed.",
          "Put on the new diaper.",
          "Dispose of the dirty one.",
        ],
        videoUrl: "https://example.com/quick-diaper-change",
      },
      {
        id: "soothing-crying-baby",
        title: "Soothing a Crying Baby",
        description: "Try swaddling, gentle rocking, or white noise to calm your baby.",
        image: { uri: "https://placehold.co/300x200/1E90FF/FFFFFF?text=Resource" },
        fullContent: "When your baby cries, try swaddling them snugly in a soft blanket, gently rock them in your arms, or play white noise to mimic the womb environment. Sometimes a change of position or a quiet environment can also help calm them down.",
        steps: [
          "Check for basic needs (hunger, diaper, temperature).",
          "Swaddle the baby snugly.",
          "Rock gently or walk around.",
          "Play white noise or soft music.",
          "Offer a pacifier if appropriate.",
          "Stay calm and patient.",
        ],
        videoUrl: "https://example.com/soothing-crying-baby",
      },
      {
        id: "encouraging-crawling-hacks",
        title: "Encouraging Crawling",
        description: "Place toys just out of reach to motivate your baby to crawl.",
        image: { uri: "https://placehold.co/300x200/1E90FF/FFFFFF?text=Resource" },
        fullContent: "Place toys just out of reach to motivate your baby to crawl. Create a safe space with soft surfaces and interesting objects at various distances to encourage movement and exploration.",
        steps: [
          "Create a safe crawling area.",
          "Place favorite toys just out of reach.",
          "Get down on the floor with your baby.",
          "Demonstrate crawling movements.",
          "Celebrate small progress.",
          "Practice daily for short sessions.",
        ],
        videoUrl: "https://example.com/encouraging-crawling",
      },
      {
        id: "playing-with-toys",
        title: "Playing with Toys",
        description: "Introduce sensory toys to spark curiosity and coordination.",
        image: { uri: "https://placehold.co/300x200/1E90FF/FFFFFF?text=Resource" },
        fullContent: "Introduce sensory toys with different textures, colors, and sounds to spark curiosity and develop hand-eye coordination. Rotate toys regularly to maintain interest and encourage exploration.",
        steps: [
          "Choose age-appropriate toys.",
          "Introduce one toy at a time.",
          "Demonstrate how to use the toy.",
          "Allow free exploration.",
          "Rotate toys to maintain interest.",
          "Join in the play for bonding.",
        ],
        videoUrl: "https://example.com/playing-with-toys",
      },
      {
        id: "baby-language-basics",
        title: "Baby Language",
        description: "Repeat simple words and sounds to encourage early speech.",
        image: { uri: "https://placehold.co/600x400/8A2BE2/FFFFFF?text=Baby+Language" },
        fullContent: "Talk to your baby often and repeat simple words to encourage speech development. Use clear pronunciation, make eye contact, and respond to their coos and babbles to build communication skills.",
        steps: [
          "Talk to your baby throughout the day.",
          "Use simple, clear words.",
          "Make eye contact while speaking.",
          "Respond to their sounds.",
          "Read books together daily.",
          "Sing songs and nursery rhymes.",
        ],
        videoUrl: "https://example.com/baby-language",
      },
      {
        id: "baby-cottage-setup",
        title: "Baby Cottage",
        description: "Create a cozy nook with soft lighting for bedtime routines.",
        image: { uri: "https://placehold.co/600x400/FF7F50/FFFFFF?text=Baby+Cottage" },
        fullContent: "Create a cozy nook with soft lighting, comfortable seating, and calming decor for peaceful bedtime routines. Keep the space clutter-free and dedicated to quiet activities.",
        steps: [
          "Choose a quiet corner of the room.",
          "Install dimmable or soft lighting.",
          "Add comfortable seating.",
          "Keep the area clutter-free.",
          "Use calming colors and decor.",
          "Make it a screen-free zone.",
        ],
        videoUrl: "https://example.com/baby-cottage",
      },
      {
        id: "sleep-routine-starter",
        title: "Creating a Sleep Routine",
        description: "Wind down with a warm bath and lullaby to signal bedtime.",
        image: { uri: "https://placehold.co/300x200/1E90FF/FFFFFF?text=Resource" },
        fullContent: "Wind down with a warm bath, gentle massage, and a lullaby to signal bedtime. Consistency is key—follow the same sequence every night to help your baby recognize it's time to sleep.",
        steps: [
          "Set a consistent bedtime.",
          "Give a warm bath.",
          "Put on comfortable sleepwear.",
          "Dim the lights.",
          "Sing a lullaby or read a story.",
          "Place baby in crib while drowsy.",
        ],
        videoUrl: "https://example.com/sleep-routine",
      },
    ],
  },
  {
    id: "quick-recipes",
    title: "Quick Recipes",
    categoryId: "recipe",
    searchPlaceholder: "Search for recipes",
    resources: [
      {
        id: "easy-smoothie",
        title: "Easy Smoothie",
        description: "Whip up a vitamin-rich smoothie to keep energy levels up.",
        image: { uri: "https://placehold.co/600x400/32CD32/FFFFFF?text=Easy+Smoothie" },
        fullContent: "Blend your favourite fruits with yogurt or milk for a quick, nutrient-dense drink. Add spinach or nut butter for extra vitamins and healthy fats.",
        steps: [
          "Add 1 cup fruit (fresh or frozen) to blender.",
          "Add 1/2 cup yogurt or milk of choice.",
          "Optional: add a handful of spinach or 1 tbsp nut butter.",
          "Blend until smooth and enjoy immediately.",
        ],
      },
      {
        id: "avocado-toast",
        title: "Avocado Toast",
        description: "Layer avocado on toast for a fast, filling bite.",
        image: { uri: "https://placehold.co/600x400/FFA500/FFFFFF?text=Avocado+Toast" },
        fullContent: "Mash ripe avocado with a pinch of salt and lemon juice, then spread it on whole-grain toast. Top with seeds, a drizzle of olive oil, or a poached egg for extra protein.",
        steps: [
          "Toast a slice of whole-grain bread.",
          "Mash 1/2 avocado with salt and lemon.",
          "Spread avocado on toast and add toppings.",
          "Serve immediately.",
        ],
      },
      {
        id: "overnight-oats",
        title: "Overnight Oats",
        description: "Prep oats with berries for a grab-and-go breakfast.",
        image: { uri: "https://placehold.co/600x400/1E90FF/FFFFFF?text=Overnight+Oats" },
        fullContent: "Combine rolled oats with milk or yogurt, add a sweetener and fruit, then refrigerate overnight for an easy, nutritious breakfast.",
        steps: [
          "Mix 1/2 cup rolled oats with 1/2 cup milk or yogurt.",
          "Add 1 tsp sweetener and a handful of berries.",
          "Cover and refrigerate overnight.",
          "Stir and eat cold or warmed in the morning.",
        ],
      },
    ],
  },
  {
    id: "child-development",
    title: "Child Development",
    categoryId: "parenting",
    searchPlaceholder: "Search developmental tips",
    resources: [
      {
        id: "encouraging-crawling",
        title: "Encouraging Crawling",
        description: "Place toys just out of reach to motivate your baby to crawl.",
        image: { uri: "https://placehold.co/600x400/20B2AA/FFFFFF?text=Encouraging+Crawling" },
        fullContent: "Create a safe, inviting floor space and place favourite toys just beyond reach to motivate movement and exploration. Encourage short, frequent sessions and celebrate attempts.",
        steps: [
          "Set up a soft, safe play area.",
          "Place toys slightly out of reach.",
          "Get down to the baby's level and encourage movement.",
          "Offer praise for attempts and progress.",
        ],
      },
      {
        id: "first-words",
        title: "First Words",
        description: "Talk to your baby often and repeat simple words to encourage speech.",
        image: { uri: "https://placehold.co/600x400/9370DB/FFFFFF?text=First+Words" },
        fullContent: "Narrate daily routines, read aloud, and repeat words to help your baby connect sounds with meaning. Respond to their vocalizations to reinforce communication.",
        steps: [
          "Narrate what you're doing throughout the day.",
          "Read simple books together regularly.",
          "Repeat and expand on your baby's vocalizations.",
          "Use gestures along with words.",
        ],
      },
      {
        id: "tummy-time",
        title: "Tummy Time Essentials",
        description: "Strengthen core muscles with short, frequent tummy time sessions.",
        image: { uri: "https://placehold.co/600x400/FF69B4/FFFFFF?text=Tummy+Time" },
        fullContent: "Start with short tummy time sessions while your baby is awake and alert to build neck and upper-body strength. Gradually increase duration and make it engaging with toys.",
        steps: [
          "Begin with 1-2 minutes several times a day.",
          "Place toys or mirrors to encourage reaching.",
          "Stay close and supervise at all times.",
          "Increase session length slowly as tolerated.",
        ],
      },
    ],
  },
];
