import { Category, ResourceSectionData } from "./types";

export const categories: Category[] = [
  { id: "all", label: "All" },
  { id: "parenting", label: "Parenting" },
  { id: "selfCare", label: "Self-care" },
  { id: "recipe", label: "Quick recipe" },
];

// Temporary demo data matching the design; replace with API payloads once available.
export const resourceSections: ResourceSectionData[] = [
  {
    id: "parenting-hacks",
    title: "Parenting Hacks",
    categoryId: "parenting",
    searchPlaceholder: "Search for Parenting tips",
    resources: [
      {
        id: "quick-diaper",
        title: "Quick Diaper Change",
        description: "Use a portable changing pad and keep essentials organized.",
        image: { uri: "https://placehold.co/300x200/1E90FF/FFFFFF?text=Resource" },
        fullContent: "Lay out supplies, keep one hand on the baby, clean front to back, let skin dry, apply cream if needed, fasten a fresh diaper snugly, and dispose of the dirty one.",
        steps: [
          "Prep first.",
          "Lay the baby down safely.",
          "Clean thoroughly.",
          "Apply cream if needed.",
          "Put on the new diaper.",
          "Dispose of the dirty one.",
        ],
        videoUrl: "https://example.com/quick-diaper-change",
      },
      {
        id: "soothing-crying-baby",
        title: "Soothing a Crying Baby",
        description: "Try swaddling, gentle rocking, or white noise to calm your baby.",
        image: { uri: "https://placehold.co/300x200/1E90FF/FFFFFF?text=Resource" },
        fullContent: "When your baby cries, try swaddling them snugly in a soft blanket, gently rock them in your arms, or play white noise to mimic the womb environment. Sometimes a change of position or a quiet environment can also help calm them down.",
        steps: [
          "Check for basic needs (hunger, diaper, temperature).",
          "Swaddle the baby snugly.",
          "Rock gently or walk around.",
          "Play white noise or soft music.",
          "Offer a pacifier if appropriate.",
          "Stay calm and patient.",
        ],
        videoUrl: "https://example.com/soothing-crying-baby",
      },
      {
        id: "encouraging-crawling-hacks",
        title: "Encouraging Crawling",
        description: "Place toys just out of reach to motivate your baby to crawl.",
        image: { uri: "https://placehold.co/300x200/1E90FF/FFFFFF?text=Resource" },
        fullContent: "Place toys just out of reach to motivate your baby to crawl. Create a safe space with soft surfaces and interesting objects at various distances to encourage movement and exploration.",
        steps: [
          "Create a safe crawling area.",
          "Place favorite toys just out of reach.",
          "Get down on the floor with your baby.",
          "Demonstrate crawling movements.",
          "Celebrate small progress.",
          "Practice daily for short sessions.",
        ],
        videoUrl: "https://example.com/encouraging-crawling",
      },
      {
        id: "playing-with-toys",
        title: "Playing with Toys",
        description: "Introduce sensory toys to spark curiosity and coordination.",
        image: { uri: "https://placehold.co/300x200/1E90FF/FFFFFF?text=Resource" },
        fullContent: "Introduce sensory toys with different textures, colors, and sounds to spark curiosity and develop hand-eye coordination. Rotate toys regularly to maintain interest and encourage exploration.",
        steps: [
          "Choose age-appropriate toys.",
          "Introduce one toy at a time.",
          "Demonstrate how to use the toy.",
          "Allow free exploration.",
          "Rotate toys to maintain interest.",
          "Join in the play for bonding.",
        ],
        videoUrl: "https://example.com/playing-with-toys",
      },
      {
        id: "baby-language-basics",
        title: "Baby language",
        description: "Repeat simple words and sounds to encourage early speech.",
        image: { uri: "https://placehold.co/300x200/1E90FF/FFFFFF?text=Resource" },
        fullContent: "Talk to your baby often and repeat simple words to encourage speech development. Use clear pronunciation, make eye contact, and respond to their coos and babbles to build communication skills.",
        steps: [
          "Talk to your baby throughout the day.",
          "Use simple, clear words.",
          "Make eye contact while speaking.",
          "Respond to their sounds.",
          "Read books together daily.",
          "Sing songs and nursery rhymes.",
        ],
        videoUrl: "https://example.com/baby-language",
      },
      {
        id: "baby-cottage-setup",
        title: "Baby cottage",
        description: "Create a cozy nook with soft lighting for bedtime routines.",
        image: { uri: "https://placehold.co/300x200/1E90FF/FFFFFF?text=Resource" },
        fullContent: "Create a cozy nook with soft lighting, comfortable seating, and calming decor for peaceful bedtime routines. Keep the space clutter-free and dedicated to quiet activities.",
        steps: [
          "Choose a quiet corner of the room.",
          "Install dimmable or soft lighting.",
          "Add comfortable seating.",
          "Keep the area clutter-free.",
          "Use calming colors and decor.",
          "Make it a screen-free zone.",
        ],
        videoUrl: "https://example.com/baby-cottage",
      },
      {
        id: "sleep-routine-starter",
        title: "Creating a Sleep Routine",
        description: "Wind down with a warm bath and lullaby to signal bedtime.",
        image: { uri: "https://placehold.co/300x200/1E90FF/FFFFFF?text=Resource" },
        fullContent: "Wind down with a warm bath, gentle massage, and a lullaby to signal bedtime. Consistency is key—follow the same sequence every night to help your baby recognize it's time to sleep.",
        steps: [
          "Set a consistent bedtime.",
          "Give a warm bath.",
          "Put on comfortable sleepwear.",
          "Dim the lights.",
          "Sing a lullaby or read a story.",
          "Place baby in crib while drowsy.",
        ],
        videoUrl: "https://example.com/sleep-routine",
      },
    ],
  },
  {
    id: "quick-recipes",
    title: "Quick Recipes",
    categoryId: "recipe",
    searchPlaceholder: "Search for recipes",
    resources: [
      {
        id: "easy-smoothie",
        title: "Easy Smoothie",
        description: "Whip up a vitamin-rich smoothie to keep energy levels up.",
        image: { uri: "https://placehold.co/300x200/1E90FF/FFFFFF?text=Resource" },
      },
      {
        id: "avocado-toast",
        title: "Avocado Toast",
        description: "Layer avocado on toast for a fast, filling bite.",
        image: { uri: "https://placehold.co/300x200/1E90FF/FFFFFF?text=Resource" },
      },
      {
        id: "overnight-oats",
        title: "Overnight Oats",
        description: "Prep oats with berries for a grab-and-go breakfast.",
        image: { uri: "https://placehold.co/300x200/1E90FF/FFFFFF?text=Resource" },
      },
    ],
  },
  {
    id: "child-development",
    title: "Child Development",
    categoryId: "parenting",
    searchPlaceholder: "Search developmental tips",
    resources: [
      {
        id: "encouraging-crawling",
        title: "Encouraging Crawling",
        description: "Place toys just out of reach to motivate your baby to crawl.",
        image: { uri: "https://placehold.co/300x200/1E90FF/FFFFFF?text=Resource" },
      },
      {
        id: "first-words",
        title: "First Words",
        description: "Talk to your baby often and repeat simple words to encourage speech.",
        image: { uri: "https://placehold.co/300x200/1E90FF/FFFFFF?text=Resource" },
      },
      {
        id: "tummy-time",
        title: "Tummy Time Essentials",
        description: "Strengthen core muscles with short, frequent tummy time sessions.",
        image: { uri: "https://placehold.co/300x200/1E90FF/FFFFFF?text=Resource" },
      },
    ],
  },
];
